// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\HyperlinkController::index
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:16
 * @route "/hyperlinks"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/hyperlinks",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\HyperlinkController::index
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:16
 * @route "/hyperlinks"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\HyperlinkController::index
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:16
 * @route "/hyperlinks"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::index
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:16
 * @route "/hyperlinks"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\HyperlinkController::index
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:16
 * @route "/hyperlinks"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::index
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:16
 * @route "/hyperlinks"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::index
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:16
 * @route "/hyperlinks"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})



index.form = indexForm
/**
 * @see \App\Http\Controllers\HyperlinkController::create
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:28
 * @route "/hyperlinks/create"
 */
export const create = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: create.url(options),
    method: "get",
})

create.definition = {
    methods: ["get","head"],
    url: "/hyperlinks/create",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\HyperlinkController::create
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:28
 * @route "/hyperlinks/create"
 */
create.url = (options?: RouteQueryOptions) => {
    return create.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\HyperlinkController::create
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:28
 * @route "/hyperlinks/create"
 */
create.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: create.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::create
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:28
 * @route "/hyperlinks/create"
 */
create.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: create.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\HyperlinkController::create
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:28
 * @route "/hyperlinks/create"
 */
const createForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: create.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::create
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:28
 * @route "/hyperlinks/create"
 */
createForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: create.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::create
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:28
 * @route "/hyperlinks/create"
 */
createForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: create.url(formSafeOptions("head", options)),
    method: "get",
})



create.form = createForm
/**
 * @see \App\Http\Controllers\HyperlinkController::store
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:39
 * @route "/hyperlinks"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/hyperlinks",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\HyperlinkController::store
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:39
 * @route "/hyperlinks"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\HyperlinkController::store
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:39
 * @route "/hyperlinks"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\HyperlinkController::store
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:39
 * @route "/hyperlinks"
 */
const storeForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::store
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:39
 * @route "/hyperlinks"
 */
storeForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})



store.form = storeForm
/**
 * @see \App\Http\Controllers\HyperlinkController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:55
 * @route "/hyperlinks/{hyperlink}"
 */
export const show = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/hyperlinks/{hyperlink}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\HyperlinkController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:55
 * @route "/hyperlinks/{hyperlink}"
 */
show.url = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { hyperlink: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { hyperlink: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        hyperlink: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        hyperlink: typeof args.hyperlink === "object" ? args.hyperlink.id : args.hyperlink,
    }
    
    return show.definition.url
        .replace("{hyperlink}", parsedArgs.hyperlink.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\HyperlinkController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:55
 * @route "/hyperlinks/{hyperlink}"
 */
show.get = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:55
 * @route "/hyperlinks/{hyperlink}"
 */
show.head = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\HyperlinkController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:55
 * @route "/hyperlinks/{hyperlink}"
 */
const showForm = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:55
 * @route "/hyperlinks/{hyperlink}"
 */
showForm.get = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:55
 * @route "/hyperlinks/{hyperlink}"
 */
showForm.head = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, formSafeOptions("head", options)),
    method: "get",
})



show.form = showForm
/**
 * @see \App\Http\Controllers\HyperlinkController::edit
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:65
 * @route "/hyperlinks/{hyperlink}/edit"
 */
export const edit = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

edit.definition = {
    methods: ["get","head"],
    url: "/hyperlinks/{hyperlink}/edit",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\HyperlinkController::edit
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:65
 * @route "/hyperlinks/{hyperlink}/edit"
 */
edit.url = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { hyperlink: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { hyperlink: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        hyperlink: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        hyperlink: typeof args.hyperlink === "object" ? args.hyperlink.id : args.hyperlink,
    }
    
    return edit.definition.url
        .replace("{hyperlink}", parsedArgs.hyperlink.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\HyperlinkController::edit
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:65
 * @route "/hyperlinks/{hyperlink}/edit"
 */
edit.get = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::edit
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:65
 * @route "/hyperlinks/{hyperlink}/edit"
 */
edit.head = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: edit.url(args, options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\HyperlinkController::edit
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:65
 * @route "/hyperlinks/{hyperlink}/edit"
 */
const editForm = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::edit
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:65
 * @route "/hyperlinks/{hyperlink}/edit"
 */
editForm.get = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::edit
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:65
 * @route "/hyperlinks/{hyperlink}/edit"
 */
editForm.head = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(args, formSafeOptions("head", options)),
    method: "get",
})



edit.form = editForm
/**
 * @see \App\Http\Controllers\HyperlinkController::update
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:77
 * @route "/hyperlinks/{hyperlink}"
 */
export const update = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put","patch"],
    url: "/hyperlinks/{hyperlink}",
} satisfies RouteDefinition<["put","patch"]>

/**
 * @see \App\Http\Controllers\HyperlinkController::update
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:77
 * @route "/hyperlinks/{hyperlink}"
 */
update.url = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { hyperlink: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { hyperlink: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        hyperlink: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        hyperlink: typeof args.hyperlink === "object" ? args.hyperlink.id : args.hyperlink,
    }
    
    return update.definition.url
        .replace("{hyperlink}", parsedArgs.hyperlink.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\HyperlinkController::update
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:77
 * @route "/hyperlinks/{hyperlink}"
 */
update.put = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::update
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:77
 * @route "/hyperlinks/{hyperlink}"
 */
update.patch = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})



/**
 * @see \App\Http\Controllers\HyperlinkController::update
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:77
 * @route "/hyperlinks/{hyperlink}"
 */
const updateForm = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::update
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:77
 * @route "/hyperlinks/{hyperlink}"
 */
updateForm.put = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::update
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:77
 * @route "/hyperlinks/{hyperlink}"
 */
updateForm.patch = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("patch", options)),
    method: "post",
})



update.form = updateForm
/**
 * @see \App\Http\Controllers\HyperlinkController::destroy
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:90
 * @route "/hyperlinks/{hyperlink}"
 */
export const destroy = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/hyperlinks/{hyperlink}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\HyperlinkController::destroy
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:90
 * @route "/hyperlinks/{hyperlink}"
 */
destroy.url = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { hyperlink: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { hyperlink: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        hyperlink: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        hyperlink: typeof args.hyperlink === "object" ? args.hyperlink.id : args.hyperlink,
    }
    
    return destroy.definition.url
        .replace("{hyperlink}", parsedArgs.hyperlink.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\HyperlinkController::destroy
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:90
 * @route "/hyperlinks/{hyperlink}"
 */
destroy.delete = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})



/**
 * @see \App\Http\Controllers\HyperlinkController::destroy
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:90
 * @route "/hyperlinks/{hyperlink}"
 */
const destroyForm = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: destroy.url(args, formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\HyperlinkController::destroy
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php:90
 * @route "/hyperlinks/{hyperlink}"
 */
destroyForm.delete = (args: { hyperlink: number | { id: number } } | [ hyperlink: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: destroy.url(args, formSafeOptions("delete", options)),
    method: "post",
})



destroy.form = destroyForm

const hyperlinks = {
    index,
    create,
    store,
    show,
    edit,
    update,
    destroy,
}

export default hyperlinks