// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import AuthController from "./AuthController";
import ImageController from "./ImageController";

export const Api = {
    AuthController,
    ImageController,
}

export default Api