// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import AuthController from "./AuthController";

export const Api = {
    AuthController,
}

export default Api