// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Fortify from "./Fortify";
import Sanctum from "./Sanctum";

export const Laravel = {
    Fortify,
    Sanctum,
}

export default Laravel