// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Sanctum from "./Sanctum";
import Fortify from "./Fortify";

export const Laravel = {
    Sanctum,
    Fortify,
}

export default Laravel