// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\sanctum\src\Http\Controllers\CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
export const show = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/sanctum/csrf-cookie",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\sanctum\src\Http\Controllers\CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
show.url = (options?: RouteQueryOptions) => {
    return show.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\sanctum\src\Http\Controllers\CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
show.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(options),
    method: "get",
})

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\sanctum\src\Http\Controllers\CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
show.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(options),
    method: "head",
})



/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\sanctum\src\Http\Controllers\CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
const showForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(options),
    method: "get",
})

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\sanctum\src\Http\Controllers\CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
showForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(options),
    method: "get",
})

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\sanctum\src\Http\Controllers\CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
showForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(formSafeOptions("head", options)),
    method: "get",
})



show.form = showForm

const CsrfCookieController = {
    show,
}

export default CsrfCookieController