// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import CsrfCookieController from "./CsrfCookieController";

export const Controllers = {
    CsrfCookieController,
}

export default Controllers