// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see /app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
export const csrfCookie = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: csrfCookie.url(options),
    method: "get",
})

csrfCookie.definition = {
    methods: ["get","head"],
    url: "/sanctum/csrf-cookie",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see /app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
csrfCookie.url = (options?: RouteQueryOptions) => {
    return csrfCookie.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see /app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
csrfCookie.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: csrfCookie.url(options),
    method: "get",
})

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see /app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
csrfCookie.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: csrfCookie.url(options),
    method: "head",
})



/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see /app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
const csrfCookieForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: csrfCookie.url(options),
    method: "get",
})

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see /app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
csrfCookieForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: csrfCookie.url(options),
    method: "get",
})

/**
 * @see \Laravel\Sanctum\Http\Controllers\CsrfCookieController::show
 * @see /app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php:17
 * @route "/sanctum/csrf-cookie"
 */
csrfCookieForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: csrfCookie.url(formSafeOptions("head", options)),
    method: "get",
})



csrfCookie.form = csrfCookieForm

const sanctum = {
    "csrf-cookie": csrfCookie,
}

export default sanctum