// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import ProfileController from "./ProfileController";
import TwoFactorAuthenticationController from "./TwoFactorAuthenticationController";
import PasswordController from "./PasswordController";

export const Settings = {
    ProfileController,
    TwoFactorAuthenticationController,
    PasswordController,
}

export default Settings