// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Status from "./Status";
import Season from "./Season";

export const Enums = {
    Status,
    Season,
}

export default Enums