// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Season from "./Season";
import Status from "./Status";

export const Enums = {
    Season,
    Status,
}

export default Enums