// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Status from "./Status";

export const Enums = {
    Status,
}

export default Enums