// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Draft = "draft"
export const Published = "published"
export const Archived = "archived"

/**
 * @see [App\Enums\Status](C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Enums\Status.php)
 */
export const Status = { Draft, Published, Archived } as const

export default Status