// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";
import cache from "./cache";
import queries from "./queries";

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:18
 * @route "/_debugbar/open"
 */
export const openhandler = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: openhandler.url(options),
    method: "get",
})

openhandler.definition = {
    methods: ["get","head"],
    url: "/_debugbar/open",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:18
 * @route "/_debugbar/open"
 */
openhandler.url = (options?: RouteQueryOptions) => {
    return openhandler.definition.url + queryParams(options)
}

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:18
 * @route "/_debugbar/open"
 */
openhandler.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: openhandler.url(options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:18
 * @route "/_debugbar/open"
 */
openhandler.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: openhandler.url(options),
    method: "head",
})



/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:18
 * @route "/_debugbar/open"
 */
const openhandlerForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: openhandler.url(options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:18
 * @route "/_debugbar/open"
 */
openhandlerForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: openhandler.url(options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:18
 * @route "/_debugbar/open"
 */
openhandlerForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: openhandler.url(formSafeOptions("head", options)),
    method: "get",
})



openhandler.form = openhandlerForm
/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:49
 * @route "/_debugbar/clockwork/{id}"
 */
export const clockwork = (args: { id: string | number } | [ id: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: clockwork.url(args, options),
    method: "get",
})

clockwork.definition = {
    methods: ["get","head"],
    url: "/_debugbar/clockwork/{id}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:49
 * @route "/_debugbar/clockwork/{id}"
 */
clockwork.url = (args: { id: string | number } | [ id: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { id: args }
}
    
    if (Array.isArray(args)) {
    args = {
        id: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        id: args.id,
    }
    
    return clockwork.definition.url
        .replace("{id}", parsedArgs.id.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:49
 * @route "/_debugbar/clockwork/{id}"
 */
clockwork.get = (args: { id: string | number } | [ id: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: clockwork.url(args, options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:49
 * @route "/_debugbar/clockwork/{id}"
 */
clockwork.head = (args: { id: string | number } | [ id: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: clockwork.url(args, options),
    method: "head",
})



/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:49
 * @route "/_debugbar/clockwork/{id}"
 */
const clockworkForm = (args: { id: string | number } | [ id: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: clockwork.url(args, options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:49
 * @route "/_debugbar/clockwork/{id}"
 */
clockworkForm.get = (args: { id: string | number } | [ id: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: clockwork.url(args, options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php:49
 * @route "/_debugbar/clockwork/{id}"
 */
clockworkForm.head = (args: { id: string | number } | [ id: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: clockwork.url(args, formSafeOptions("head", options)),
    method: "get",
})



clockwork.form = clockworkForm
/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:16
 * @route "/_debugbar/assets"
 */
export const assets = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: assets.url(options),
    method: "get",
})

assets.definition = {
    methods: ["get","head"],
    url: "/_debugbar/assets",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:16
 * @route "/_debugbar/assets"
 */
assets.url = (options?: RouteQueryOptions) => {
    return assets.definition.url + queryParams(options)
}

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:16
 * @route "/_debugbar/assets"
 */
assets.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: assets.url(options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:16
 * @route "/_debugbar/assets"
 */
assets.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: assets.url(options),
    method: "head",
})



/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:16
 * @route "/_debugbar/assets"
 */
const assetsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: assets.url(options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:16
 * @route "/_debugbar/assets"
 */
assetsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: assets.url(options),
    method: "get",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:16
 * @route "/_debugbar/assets"
 */
assetsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: assets.url(formSafeOptions("head", options)),
    method: "get",
})



assets.form = assetsForm

const debugbar = {
    openhandler,
    clockwork,
    assets,
    cache,
    queries,
}

export default debugbar