// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Http from "./Http";
import Enums from "./Enums";

export const App = {
    Http,
    Enums,
}

export default App