// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../index";

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "/login"
 */
export const login = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: login.url(options),
    method: "get",
})

login.definition = {
    methods: ["get","head"],
    url: "/login",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "/login"
 */
login.url = (options?: RouteQueryOptions) => {
    return login.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "/login"
 */
login.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: login.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "/login"
 */
login.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: login.url(options),
    method: "head",
})



/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "/login"
 */
const loginForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: login.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "/login"
 */
loginForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: login.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "/login"
 */
loginForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: login.url(formSafeOptions("head", options)),
    method: "get",
})



login.form = loginForm
/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "/logout"
 */
export const logout = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: logout.url(options),
    method: "post",
})

logout.definition = {
    methods: ["post"],
    url: "/logout",
} satisfies RouteDefinition<["post"]>

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "/logout"
 */
logout.url = (options?: RouteQueryOptions) => {
    return logout.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "/logout"
 */
logout.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: logout.url(options),
    method: "post",
})



/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "/logout"
 */
const logoutForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: logout.url(options),
    method: "post",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "/logout"
 */
logoutForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: logout.url(options),
    method: "post",
})



logout.form = logoutForm
/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:41
 * @route "/register"
 */
export const register = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: register.url(options),
    method: "get",
})

register.definition = {
    methods: ["get","head"],
    url: "/register",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:41
 * @route "/register"
 */
register.url = (options?: RouteQueryOptions) => {
    return register.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:41
 * @route "/register"
 */
register.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: register.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:41
 * @route "/register"
 */
register.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: register.url(options),
    method: "head",
})



/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:41
 * @route "/register"
 */
const registerForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: register.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:41
 * @route "/register"
 */
registerForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: register.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::create
 * @see /app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:41
 * @route "/register"
 */
registerForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: register.url(formSafeOptions("head", options)),
    method: "get",
})



register.form = registerForm
/**
 * @see \App\Http\Controllers\PageController::index
 * @see /app/app/Http/Controllers/PageController.php:11
 * @route "/"
 */
export const home = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

home.definition = {
    methods: ["get","head"],
    url: "/",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\PageController::index
 * @see /app/app/Http/Controllers/PageController.php:11
 * @route "/"
 */
home.url = (options?: RouteQueryOptions) => {
    return home.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\PageController::index
 * @see /app/app/Http/Controllers/PageController.php:11
 * @route "/"
 */
home.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::index
 * @see /app/app/Http/Controllers/PageController.php:11
 * @route "/"
 */
home.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: home.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\PageController::index
 * @see /app/app/Http/Controllers/PageController.php:11
 * @route "/"
 */
const homeForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::index
 * @see /app/app/Http/Controllers/PageController.php:11
 * @route "/"
 */
homeForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::index
 * @see /app/app/Http/Controllers/PageController.php:11
 * @route "/"
 */
homeForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(formSafeOptions("head", options)),
    method: "get",
})



home.form = homeForm
/**
 * @see \App\Http\Controllers\PageController::cookiePolicy
 * @see /app/app/Http/Controllers/PageController.php:28
 * @route "/cookie-policy"
 */
export const cookiePolicy = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: cookiePolicy.url(options),
    method: "get",
})

cookiePolicy.definition = {
    methods: ["get","head"],
    url: "/cookie-policy",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\PageController::cookiePolicy
 * @see /app/app/Http/Controllers/PageController.php:28
 * @route "/cookie-policy"
 */
cookiePolicy.url = (options?: RouteQueryOptions) => {
    return cookiePolicy.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\PageController::cookiePolicy
 * @see /app/app/Http/Controllers/PageController.php:28
 * @route "/cookie-policy"
 */
cookiePolicy.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: cookiePolicy.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::cookiePolicy
 * @see /app/app/Http/Controllers/PageController.php:28
 * @route "/cookie-policy"
 */
cookiePolicy.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: cookiePolicy.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\PageController::cookiePolicy
 * @see /app/app/Http/Controllers/PageController.php:28
 * @route "/cookie-policy"
 */
const cookiePolicyForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: cookiePolicy.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::cookiePolicy
 * @see /app/app/Http/Controllers/PageController.php:28
 * @route "/cookie-policy"
 */
cookiePolicyForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: cookiePolicy.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::cookiePolicy
 * @see /app/app/Http/Controllers/PageController.php:28
 * @route "/cookie-policy"
 */
cookiePolicyForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: cookiePolicy.url(formSafeOptions("head", options)),
    method: "get",
})



cookiePolicy.form = cookiePolicyForm
/**
 * @see \App\Http\Controllers\PageController::disclaimer
 * @see /app/app/Http/Controllers/PageController.php:24
 * @route "/disclaimer"
 */
export const disclaimer = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: disclaimer.url(options),
    method: "get",
})

disclaimer.definition = {
    methods: ["get","head"],
    url: "/disclaimer",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\PageController::disclaimer
 * @see /app/app/Http/Controllers/PageController.php:24
 * @route "/disclaimer"
 */
disclaimer.url = (options?: RouteQueryOptions) => {
    return disclaimer.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\PageController::disclaimer
 * @see /app/app/Http/Controllers/PageController.php:24
 * @route "/disclaimer"
 */
disclaimer.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: disclaimer.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::disclaimer
 * @see /app/app/Http/Controllers/PageController.php:24
 * @route "/disclaimer"
 */
disclaimer.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: disclaimer.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\PageController::disclaimer
 * @see /app/app/Http/Controllers/PageController.php:24
 * @route "/disclaimer"
 */
const disclaimerForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: disclaimer.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::disclaimer
 * @see /app/app/Http/Controllers/PageController.php:24
 * @route "/disclaimer"
 */
disclaimerForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: disclaimer.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::disclaimer
 * @see /app/app/Http/Controllers/PageController.php:24
 * @route "/disclaimer"
 */
disclaimerForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: disclaimer.url(formSafeOptions("head", options)),
    method: "get",
})



disclaimer.form = disclaimerForm
/**
 * @see \App\Http\Controllers\PageController::legalNotice
 * @see /app/app/Http/Controllers/PageController.php:20
 * @route "/legal-notice"
 */
export const legalNotice = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: legalNotice.url(options),
    method: "get",
})

legalNotice.definition = {
    methods: ["get","head"],
    url: "/legal-notice",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\PageController::legalNotice
 * @see /app/app/Http/Controllers/PageController.php:20
 * @route "/legal-notice"
 */
legalNotice.url = (options?: RouteQueryOptions) => {
    return legalNotice.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\PageController::legalNotice
 * @see /app/app/Http/Controllers/PageController.php:20
 * @route "/legal-notice"
 */
legalNotice.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: legalNotice.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::legalNotice
 * @see /app/app/Http/Controllers/PageController.php:20
 * @route "/legal-notice"
 */
legalNotice.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: legalNotice.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\PageController::legalNotice
 * @see /app/app/Http/Controllers/PageController.php:20
 * @route "/legal-notice"
 */
const legalNoticeForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: legalNotice.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::legalNotice
 * @see /app/app/Http/Controllers/PageController.php:20
 * @route "/legal-notice"
 */
legalNoticeForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: legalNotice.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::legalNotice
 * @see /app/app/Http/Controllers/PageController.php:20
 * @route "/legal-notice"
 */
legalNoticeForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: legalNotice.url(formSafeOptions("head", options)),
    method: "get",
})



legalNotice.form = legalNoticeForm
/**
 * @see \App\Http\Controllers\PageController::privatePolicy
 * @see /app/app/Http/Controllers/PageController.php:32
 * @route "/privacy-policy"
 */
export const privacyPolicy = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: privacyPolicy.url(options),
    method: "get",
})

privacyPolicy.definition = {
    methods: ["get","head"],
    url: "/privacy-policy",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\PageController::privatePolicy
 * @see /app/app/Http/Controllers/PageController.php:32
 * @route "/privacy-policy"
 */
privacyPolicy.url = (options?: RouteQueryOptions) => {
    return privacyPolicy.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\PageController::privatePolicy
 * @see /app/app/Http/Controllers/PageController.php:32
 * @route "/privacy-policy"
 */
privacyPolicy.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: privacyPolicy.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::privatePolicy
 * @see /app/app/Http/Controllers/PageController.php:32
 * @route "/privacy-policy"
 */
privacyPolicy.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: privacyPolicy.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\PageController::privatePolicy
 * @see /app/app/Http/Controllers/PageController.php:32
 * @route "/privacy-policy"
 */
const privacyPolicyForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: privacyPolicy.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::privatePolicy
 * @see /app/app/Http/Controllers/PageController.php:32
 * @route "/privacy-policy"
 */
privacyPolicyForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: privacyPolicy.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::privatePolicy
 * @see /app/app/Http/Controllers/PageController.php:32
 * @route "/privacy-policy"
 */
privacyPolicyForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: privacyPolicy.url(formSafeOptions("head", options)),
    method: "get",
})



privacyPolicy.form = privacyPolicyForm
/**
 * @see \App\Http\Controllers\PageController::termsOfService
 * @see /app/app/Http/Controllers/PageController.php:36
 * @route "/terms-of-service"
 */
export const termsOfService = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: termsOfService.url(options),
    method: "get",
})

termsOfService.definition = {
    methods: ["get","head"],
    url: "/terms-of-service",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\PageController::termsOfService
 * @see /app/app/Http/Controllers/PageController.php:36
 * @route "/terms-of-service"
 */
termsOfService.url = (options?: RouteQueryOptions) => {
    return termsOfService.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\PageController::termsOfService
 * @see /app/app/Http/Controllers/PageController.php:36
 * @route "/terms-of-service"
 */
termsOfService.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: termsOfService.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::termsOfService
 * @see /app/app/Http/Controllers/PageController.php:36
 * @route "/terms-of-service"
 */
termsOfService.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: termsOfService.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\PageController::termsOfService
 * @see /app/app/Http/Controllers/PageController.php:36
 * @route "/terms-of-service"
 */
const termsOfServiceForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: termsOfService.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::termsOfService
 * @see /app/app/Http/Controllers/PageController.php:36
 * @route "/terms-of-service"
 */
termsOfServiceForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: termsOfService.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PageController::termsOfService
 * @see /app/app/Http/Controllers/PageController.php:36
 * @route "/terms-of-service"
 */
termsOfServiceForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: termsOfService.url(formSafeOptions("head", options)),
    method: "get",
})



termsOfService.form = termsOfServiceForm
/**
 * @see /[serialized-closure]:2
 * @route "/dashboard"
 */
export const dashboard = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: dashboard.url(options),
    method: "get",
})

dashboard.definition = {
    methods: ["get","head"],
    url: "/dashboard",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see /[serialized-closure]:2
 * @route "/dashboard"
 */
dashboard.url = (options?: RouteQueryOptions) => {
    return dashboard.definition.url + queryParams(options)
}

/**
 * @see /[serialized-closure]:2
 * @route "/dashboard"
 */
dashboard.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: dashboard.url(options),
    method: "get",
})

/**
 * @see /[serialized-closure]:2
 * @route "/dashboard"
 */
dashboard.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: dashboard.url(options),
    method: "head",
})



/**
 * @see /[serialized-closure]:2
 * @route "/dashboard"
 */
const dashboardForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: dashboard.url(options),
    method: "get",
})

/**
 * @see /[serialized-closure]:2
 * @route "/dashboard"
 */
dashboardForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: dashboard.url(options),
    method: "get",
})

/**
 * @see /[serialized-closure]:2
 * @route "/dashboard"
 */
dashboardForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: dashboard.url(formSafeOptions("head", options)),
    method: "get",
})



dashboard.form = dashboardForm

const routes = {
    login,
    logout,
    register,
    home,
    "cookie-policy": cookiePolicy,
    disclaimer,
    "legal-notice": legalNotice,
    "privacy-policy": privacyPolicy,
    "terms-of-service": termsOfService,
    dashboard,
}

export default routes