// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::css
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:36
 * @route "/_debugbar/assets/stylesheets"
 */
export const css = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: css.url(options),
    method: "get",
})

css.definition = {
    methods: ["get","head"],
    url: "/_debugbar/assets/stylesheets",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::css
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:36
 * @route "/_debugbar/assets/stylesheets"
 */
css.url = (options?: RouteQueryOptions) => {
    return css.definition.url + queryParams(options)
}

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::css
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:36
 * @route "/_debugbar/assets/stylesheets"
 */
css.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: css.url(options),
    method: "get",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::css
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:36
 * @route "/_debugbar/assets/stylesheets"
 */
css.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: css.url(options),
    method: "head",
})



/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::css
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:36
 * @route "/_debugbar/assets/stylesheets"
 */
const cssForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: css.url(options),
    method: "get",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::css
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:36
 * @route "/_debugbar/assets/stylesheets"
 */
cssForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: css.url(options),
    method: "get",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::css
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:36
 * @route "/_debugbar/assets/stylesheets"
 */
cssForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: css.url(formSafeOptions("head", options)),
    method: "get",
})



css.form = cssForm
/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::js
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:14
 * @route "/_debugbar/assets/javascript"
 */
export const js = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: js.url(options),
    method: "get",
})

js.definition = {
    methods: ["get","head"],
    url: "/_debugbar/assets/javascript",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::js
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:14
 * @route "/_debugbar/assets/javascript"
 */
js.url = (options?: RouteQueryOptions) => {
    return js.definition.url + queryParams(options)
}

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::js
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:14
 * @route "/_debugbar/assets/javascript"
 */
js.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: js.url(options),
    method: "get",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::js
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:14
 * @route "/_debugbar/assets/javascript"
 */
js.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: js.url(options),
    method: "head",
})



/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::js
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:14
 * @route "/_debugbar/assets/javascript"
 */
const jsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: js.url(options),
    method: "get",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::js
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:14
 * @route "/_debugbar/assets/javascript"
 */
jsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: js.url(options),
    method: "get",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\AssetController::js
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php:14
 * @route "/_debugbar/assets/javascript"
 */
jsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: js.url(formSafeOptions("head", options)),
    method: "get",
})



js.form = jsForm

const assets = {
    css,
    js,
}

export default assets