// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\QueriesController::explain
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/QueriesController.php:17
 * @route "/_debugbar/queries/explain"
 */
export const explain = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: explain.url(options),
    method: "post",
})

explain.definition = {
    methods: ["post"],
    url: "/_debugbar/queries/explain",
} satisfies RouteDefinition<["post"]>

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\QueriesController::explain
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/QueriesController.php:17
 * @route "/_debugbar/queries/explain"
 */
explain.url = (options?: RouteQueryOptions) => {
    return explain.definition.url + queryParams(options)
}

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\QueriesController::explain
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/QueriesController.php:17
 * @route "/_debugbar/queries/explain"
 */
explain.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: explain.url(options),
    method: "post",
})



/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\QueriesController::explain
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/QueriesController.php:17
 * @route "/_debugbar/queries/explain"
 */
const explainForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: explain.url(options),
    method: "post",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\QueriesController::explain
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/QueriesController.php:17
 * @route "/_debugbar/queries/explain"
 */
explainForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: explain.url(options),
    method: "post",
})



explain.form = explainForm

const queries = {
    explain,
}

export default queries