// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

declare module '@inertiajs/core' {
    export interface InertiaConfig {
     sharedPageProps: { auth: {user: Record<string, unknown> }, sidebarOpen: boolean } 
    }
}