// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export namespace App {
    export namespace Models {
        /**
         * @see [\App\Models\App](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Models\App.php)
         */
        export type App = { id: string, title: string, url: string, target: string, description: string | null, created_by: number | null, status: App.Enums.Status, created_at: string | null, updated_at: string | null, deleted_at: string | null, creator?: App.Models.User | null, categories?: App.Models.Category[], tags?: App.Models.Tag[] }

        /**
         * @see [\App\Models\User](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Models\User.php)
         */
        export type User = { id: number, name: string, email: string, email_verified_at: string | null, password: string, two_factor_secret: string | null, two_factor_recovery_codes: string | null, two_factor_confirmed_at: string | null, remember_token: string | null, created_at: string | null, updated_at: string | null, notifications?: Illuminate.Notifications.DatabaseNotification[] }

        /**
         * @see [\App\Models\Category](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Models\Category.php)
         */
        export type Category = { id: number, name: string, slug: string, created_at: string | null, updated_at: string | null, hyperlinks?: App.Models.Hyperlink[] }

        /**
         * @see [\App\Models\Hyperlink](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Models\Hyperlink.php)
         */
        export type Hyperlink = { id: number, title: string, url: string, description: string | null, category_id: number | null, status: string, is_featured: boolean, created_by: number | null, created_at: string | null, updated_at: string | null, category?: App.Models.Category | null, author?: App.Models.User | null }

        /**
         * @see [\App\Models\Tag](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Models\Tag.php)
         */
        export type Tag = { id: number, name: string, slug: string, created_at: string | null, updated_at: string | null }
    }

    export namespace Enums {
        /**
         * @see [\App\Enums\Status](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Enums\Status.php)
         */
        export type Status = 'draft' | 'published' | 'archived'
    }

    export namespace Http {
        export namespace Controllers {
            export namespace HyperlinkController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::index](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks/index

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::index](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Create {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks/create

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Show {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks/show

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks/edit

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Request = {    title: string;
                        url: string;
                        description?: string | null;
                        category_id?: string | null;
                        status: string;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::update](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Request = {    title: string;
                        url: string;
                        description?: string | null;
                        category_id?: string | null;
                        status: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::destroy](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace Settings {
                export namespace ProfileController {
                    export namespace Edit {
                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\ProfileController.php)
                         */
                        export type Response = Inertia.Pages.Settings/profile

                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\ProfileController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Update {
                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::update](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\ProfileController.php)
                         */
                        export type Request = {    name: string;
                            email: string;}
                    }

                    export namespace Destroy {
                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::destroy](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\ProfileController.php)
                         */
                        export type Request = {    password: string;}
                    }
                }

                export namespace PasswordController {
                    export namespace Edit {
                        /**
                         * @see [\App\Http\Controllers\Settings\PasswordController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\PasswordController.php)
                         */
                        export type Response = Inertia.Pages.Settings/password

                        /**
                         * @see [\App\Http\Controllers\Settings\PasswordController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\PasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Update {
                        /**
                         * @see [\App\Http\Controllers\Settings\PasswordController::update](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\PasswordController.php)
                         */
                        export type Request = {    current_password: string;
                            password: string;}
                    }
                }

                export namespace TwoFactorAuthenticationController {
                    export namespace Show {
                        /**
                         * @see [\App\Http\Controllers\Settings\TwoFactorAuthenticationController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\TwoFactorAuthenticationController.php)
                         */
                        export type Response = Inertia.Pages.Settings/twoFactor

                        /**
                         * @see [\App\Http\Controllers\Settings\TwoFactorAuthenticationController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\TwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }
            }
        }
    }
}

export namespace Illuminate {
    export namespace Notifications {
        /**
         * @see [\Illuminate\Notifications\DatabaseNotification](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\framework\src\Illuminate\Notifications\DatabaseNotification.php)
         */
        export type DatabaseNotification = { incrementing: boolean, notifiable?: Illuminate.Notifications.DatabaseNotification | null }
    }

    export namespace Routing {
        export namespace RedirectController {
            export namespace __invoke {
                /**
                 * @see [\Illuminate\Routing\RedirectController::__invoke](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php)
                 */
                export type Request = Record<string, unknown>
            }
        }
    }
}

export namespace Inertia {
    export type SharedData = {auth: {user: App.Models.User | null }, sidebarOpen: boolean }

    export namespace Pages {
        export namespace Hyperlinks {
            /**
             * @see [\App\Http\Controllers\HyperlinkController::index](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
             */
            export type Hyperlinks/index = Inertia.SharedData & { hyperlinks: Illuminate.Pagination.LengthAwarePaginator }

            /**
             * @see [\App\Http\Controllers\HyperlinkController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
             */
            export type Hyperlinks/create = Inertia.SharedData

            /**
             * @see [\App\Http\Controllers\HyperlinkController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
             */
            export type Hyperlinks/show = Inertia.SharedData & { hyperlink: App.Models.Hyperlink }

            /**
             * @see [\App\Http\Controllers\HyperlinkController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\HyperlinkController.php)
             */
            export type Hyperlinks/edit = Inertia.SharedData & { hyperlink: App.Models.Hyperlink }
        }

        export namespace Settings {
            /**
             * @see [\App\Http\Controllers\Settings\ProfileController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\ProfileController.php)
             */
            export type Settings/profile = Inertia.SharedData & { mustVerifyEmail: boolean, status: unknown }

            /**
             * @see [\App\Http\Controllers\Settings\PasswordController::edit](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\PasswordController.php)
             */
            export type Settings/password = Inertia.SharedData

            /**
             * @see [\App\Http\Controllers\Settings\TwoFactorAuthenticationController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\app\Http\Controllers\Settings\TwoFactorAuthenticationController.php)
             */
            export type Settings/twoFactor = Inertia.SharedData & { twoFactorEnabled: unknown, requiresConfirmation: boolean }
        }
    }
}

export namespace Laravel {
    export namespace Fortify {
        export namespace Http {
            export namespace Controllers {
                export namespace TwoFactorQrCodeController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\TwoFactorQrCodeController.php)
                         */
                        export type Response = Record<string, never>

                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\TwoFactorQrCodeController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace RecoveryCodeController {
                    export namespace Index {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RecoveryCodeController::index](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\RecoveryCodeController.php)
                         */
                        export type Response = Record<string, never>

                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RecoveryCodeController::index](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\RecoveryCodeController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RecoveryCodeController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\RecoveryCodeController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace AuthenticatedSessionController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\AuthenticatedSessionController.php)
                         */
                        export type Request = {    "": string;
                            password: string;}
                    }

                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\AuthenticatedSessionController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Destroy {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\AuthenticatedSessionController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace PasswordResetLinkController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\PasswordResetLinkController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\PasswordResetLinkController.php)
                         */
                        export type Request = {    "": string;}
                    }

                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\PasswordResetLinkController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\PasswordResetLinkController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace NewPasswordController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\NewPasswordController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\NewPasswordController.php)
                         */
                        export type Request = {    token: string;
                            "": string;
                            password: string;}
                    }

                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\NewPasswordController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\NewPasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace TwoFactorAuthenticatedSessionController {
                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\TwoFactorAuthenticatedSessionController.php)
                         */
                        export type Request = {    code?: string | null;
                            recovery_code?: string | null;}
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\TwoFactorAuthenticatedSessionController.php)
                         */
                        export type Request = {    code?: string | null;
                            recovery_code?: string | null;}
                    }
                }

                export namespace RegisteredUserController {
                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RegisteredUserController::create](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\RegisteredUserController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RegisteredUserController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\RegisteredUserController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace EmailVerificationPromptController {
                    export namespace __invoke {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\EmailVerificationPromptController::__invoke](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\EmailVerificationPromptController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace VerifyEmailController {
                    export namespace __invoke {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\VerifyEmailController::__invoke](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\VerifyEmailController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace EmailVerificationNotificationController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\EmailVerificationNotificationController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\EmailVerificationNotificationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace ConfirmablePasswordController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmablePasswordController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\ConfirmablePasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmablePasswordController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\ConfirmablePasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace ConfirmedPasswordStatusController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\ConfirmedPasswordStatusController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace TwoFactorAuthenticationController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\TwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Destroy {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController::destroy](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\TwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace ConfirmedTwoFactorAuthenticationController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmedTwoFactorAuthenticationController::store](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\ConfirmedTwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace TwoFactorSecretKeyController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorSecretKeyController::show](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\fortify\src\Http\Controllers\TwoFactorSecretKeyController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }
            }
        }
    }
}

export namespace Barryvdh {
    export namespace Debugbar {
        export namespace Controllers {
            export namespace OpenHandlerController {
                export namespace Handle {
                    /**
                     * @see [\Barryvdh\Debugbar\Controllers\OpenHandlerController::handle](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Clockwork {
                    /**
                     * @see [\Barryvdh\Debugbar\Controllers\OpenHandlerController::clockwork](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\OpenHandlerController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace AssetController {
                export namespace Css {
                    /**
                     * @see [\Barryvdh\Debugbar\Controllers\AssetController::css](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Js {
                    /**
                     * @see [\Barryvdh\Debugbar\Controllers\AssetController::js](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\AssetController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace CacheController {
                export namespace Delete {
                    /**
                     * @see [\Barryvdh\Debugbar\Controllers\CacheController::delete](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\CacheController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace QueriesController {
                export namespace Explain {
                    /**
                     * @see [\Barryvdh\Debugbar\Controllers\QueriesController::explain](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\QueriesController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }
        }
    }
}

export namespace Closure {
    export namespace __invoke {
        /**
         * @see [\Closure::__invoke](\C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\laravel\boost\src\BoostServiceProvider.php)
         */
        export type Request = Record<string, unknown>
    }
}