// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export namespace App {
    export namespace Models {
        /**
         * @see [\App\Models\App](/app/app/Models/App.php)
         */
        export type App = Record<string, never>

        /**
         * @see [\App\Models\Category](/app/app/Models/Category.php)
         */
        export type Category = Record<string, never>

        /**
         * @see [\App\Models\Hyperlink](/app/app/Models/Hyperlink.php)
         */
        export type Hyperlink = Record<string, never>

        /**
         * @see [\App\Models\Tag](/app/app/Models/Tag.php)
         */
        export type Tag = Record<string, never>

        /**
         * @see [\App\Models\User](/app/app/Models/User.php)
         */
        export type User = Record<string, never>
    }

    export namespace Enums {
        /**
         * @see [\App\Enums\Season](/app/app/Enums/Season.php)
         */
        export type Season = 'spring' | 'summer' | 'autumn' | 'winter'

        /**
         * @see [\App\Enums\Status](/app/app/Enums/Status.php)
         */
        export type Status = 'draft' | 'published' | 'archived'
    }

    export namespace Http {
        export namespace Controllers {
            export namespace PageController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\PageController::index](/app/app/Http/Controllers/PageController.php)
                     */
                    export type Response = Inertia.Pages.Welcome

                    /**
                     * @see [\App\Http\Controllers\PageController::index](/app/app/Http/Controllers/PageController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace CookiePolicy {
                    /**
                     * @see [\App\Http\Controllers\PageController::cookiePolicy](/app/app/Http/Controllers/PageController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Disclaimer {
                    /**
                     * @see [\App\Http\Controllers\PageController::disclaimer](/app/app/Http/Controllers/PageController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace LegalNotice {
                    /**
                     * @see [\App\Http\Controllers\PageController::legalNotice](/app/app/Http/Controllers/PageController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace PrivatePolicy {
                    /**
                     * @see [\App\Http\Controllers\PageController::privatePolicy](/app/app/Http/Controllers/PageController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace TermsOfService {
                    /**
                     * @see [\App\Http\Controllers\PageController::termsOfService](/app/app/Http/Controllers/PageController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace AppController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\AppController::index](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Response = Inertia.Pages.Apps.Index

                    /**
                     * @see [\App\Http\Controllers\AppController::index](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Create {
                    /**
                     * @see [\App\Http\Controllers\AppController::create](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Response = Inertia.Pages.Apps.Create

                    /**
                     * @see [\App\Http\Controllers\AppController::create](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Show {
                    /**
                     * @see [\App\Http\Controllers\AppController::show](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Response = Inertia.Pages.Apps.Show

                    /**
                     * @see [\App\Http\Controllers\AppController::show](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\AppController::edit](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Response = Inertia.Pages.Apps.Edit

                    /**
                     * @see [\App\Http\Controllers\AppController::edit](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Reorder {
                    /**
                     * @see [\App\Http\Controllers\AppController::reorder](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = {    order: unknown[];
                        "order.*"?: string;}
                }

                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\AppController::store](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = {    title: string;
                        url: string;
                        target: string;
                        position?: number | null;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\AppController::update](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = {    title?: string;
                        url?: string;
                        target?: string;
                        position?: number;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\AppController::destroy](/app/app/Http/Controllers/AppController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace HyperlinkController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::index](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks.Index

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::index](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Create {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::create](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks.Create

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::create](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Show {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::show](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks.Show

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::show](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::edit](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Response = Inertia.Pages.Hyperlinks.Edit

                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::edit](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::store](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Request = {    title: string;
                        url: string;
                        description?: string | null;
                        category_id?: string | null;
                        status: string;
                        tags?: unknown[] | null;
                        "tags.*"?: string;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::update](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Request = {    title: string;
                        url: string;
                        description?: string | null;
                        category_id?: string | null;
                        status: string;
                        tags?: unknown[] | null;
                        "tags.*"?: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\HyperlinkController::destroy](/app/app/Http/Controllers/HyperlinkController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace Settings {
                export namespace ProfileController {
                    export namespace Edit {
                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::edit](/app/app/Http/Controllers/Settings/ProfileController.php)
                         */
                        export type Response = Inertia.Pages.Settings.Profile

                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::edit](/app/app/Http/Controllers/Settings/ProfileController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Update {
                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::update](/app/app/Http/Controllers/Settings/ProfileController.php)
                         */
                        export type Request = {    name: string;
                            email: string;}
                    }

                    export namespace Destroy {
                        /**
                         * @see [\App\Http\Controllers\Settings\ProfileController::destroy](/app/app/Http/Controllers/Settings/ProfileController.php)
                         */
                        export type Request = {    password: string;}
                    }
                }

                export namespace PasswordController {
                    export namespace Edit {
                        /**
                         * @see [\App\Http\Controllers\Settings\PasswordController::edit](/app/app/Http/Controllers/Settings/PasswordController.php)
                         */
                        export type Response = Inertia.Pages.Settings.Password

                        /**
                         * @see [\App\Http\Controllers\Settings\PasswordController::edit](/app/app/Http/Controllers/Settings/PasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Update {
                        /**
                         * @see [\App\Http\Controllers\Settings\PasswordController::update](/app/app/Http/Controllers/Settings/PasswordController.php)
                         */
                        export type Request = {    current_password: string;
                            password: string;}
                    }
                }

                export namespace TwoFactorAuthenticationController {
                    export namespace Show {
                        /**
                         * @see [\App\Http\Controllers\Settings\TwoFactorAuthenticationController::show](/app/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php)
                         */
                        export type Response = Inertia.Pages.Settings.TwoFactor

                        /**
                         * @see [\App\Http\Controllers\Settings\TwoFactorAuthenticationController::show](/app/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }
            }

            export namespace Api {
                export namespace AuthController {
                    export namespace Login {
                        /**
                         * @see [\App\Http\Controllers\Api\AuthController::login](/app/app/Http/Controllers/Api/AuthController.php)
                         */
                        export type Request = {    email: string;
                            password: string;
                            device_name?: string | null;}
                    }

                    export namespace Me {
                        /**
                         * @see [\App\Http\Controllers\Api\AuthController::me](/app/app/Http/Controllers/Api/AuthController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Logout {
                        /**
                         * @see [\App\Http\Controllers\Api\AuthController::logout](/app/app/Http/Controllers/Api/AuthController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }
            }
        }
    }
}

export namespace Inertia {
    export type SharedData = {auth: {user: App.Models.User | null }, sidebarOpen: boolean }

    export namespace Pages {
        /**
         * @see [\App\Http\Controllers\PageController::index](/app/app/Http/Controllers/PageController.php)
         */
        export type Welcome = Inertia.SharedData & { hyperlinks: unknown, canRegister: true }

        export namespace Apps {
            /**
             * @see [\App\Http\Controllers\AppController::index](/app/app/Http/Controllers/AppController.php)
             */
            export type Index = Inertia.SharedData & { apps: unknown }

            /**
             * @see [\App\Http\Controllers\AppController::create](/app/app/Http/Controllers/AppController.php)
             */
            export type Create = Inertia.SharedData

            /**
             * @see [\App\Http\Controllers\AppController::show](/app/app/Http/Controllers/AppController.php)
             */
            export type Show = Inertia.SharedData & { app: App.Models.App }

            /**
             * @see [\App\Http\Controllers\AppController::edit](/app/app/Http/Controllers/AppController.php)
             */
            export type Edit = Inertia.SharedData & { app: App.Models.App }
        }

        export namespace Hyperlinks {
            /**
             * @see [\App\Http\Controllers\HyperlinkController::index](/app/app/Http/Controllers/HyperlinkController.php)
             */
            export type Index = Inertia.SharedData & { hyperlinks: Illuminate.Pagination.LengthAwarePaginator }

            /**
             * @see [\App\Http\Controllers\HyperlinkController::create](/app/app/Http/Controllers/HyperlinkController.php)
             */
            export type Create = Inertia.SharedData & { categories: unknown, tags: unknown }

            /**
             * @see [\App\Http\Controllers\HyperlinkController::show](/app/app/Http/Controllers/HyperlinkController.php)
             */
            export type Show = Inertia.SharedData & { hyperlink: App.Models.Hyperlink }

            /**
             * @see [\App\Http\Controllers\HyperlinkController::edit](/app/app/Http/Controllers/HyperlinkController.php)
             */
            export type Edit = Inertia.SharedData & { hyperlink: App.Models.Hyperlink, categories: unknown, tags: unknown }
        }

        export namespace Settings {
            /**
             * @see [\App\Http\Controllers\Settings\ProfileController::edit](/app/app/Http/Controllers/Settings/ProfileController.php)
             */
            export type Profile = Inertia.SharedData & { mustVerifyEmail: boolean, status: unknown }

            /**
             * @see [\App\Http\Controllers\Settings\PasswordController::edit](/app/app/Http/Controllers/Settings/PasswordController.php)
             */
            export type Password = Inertia.SharedData

            /**
             * @see [\App\Http\Controllers\Settings\TwoFactorAuthenticationController::show](/app/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php)
             */
            export type TwoFactor = Inertia.SharedData & { twoFactorEnabled: unknown, requiresConfirmation: boolean }
        }
    }
}

export namespace Laravel {
    export namespace Fortify {
        export namespace Http {
            export namespace Controllers {
                export namespace TwoFactorQrCodeController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show](/app/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php)
                         */
                        export type Response = Record<string, never>

                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show](/app/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace RecoveryCodeController {
                    export namespace Index {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RecoveryCodeController::index](/app/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php)
                         */
                        export type Response = Record<string, never>

                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RecoveryCodeController::index](/app/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RecoveryCodeController::store](/app/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace AuthenticatedSessionController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::store](/app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php)
                         */
                        export type Request = {    "": string;
                            password: string;}
                    }

                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create](/app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Destroy {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy](/app/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace PasswordResetLinkController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\PasswordResetLinkController::store](/app/vendor/laravel/fortify/src/Http/Controllers/PasswordResetLinkController.php)
                         */
                        export type Request = {    "": string;}
                    }

                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\PasswordResetLinkController::create](/app/vendor/laravel/fortify/src/Http/Controllers/PasswordResetLinkController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace NewPasswordController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\NewPasswordController::store](/app/vendor/laravel/fortify/src/Http/Controllers/NewPasswordController.php)
                         */
                        export type Request = {    token: string;
                            "": string;
                            password: string;}
                    }

                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\NewPasswordController::create](/app/vendor/laravel/fortify/src/Http/Controllers/NewPasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace TwoFactorAuthenticatedSessionController {
                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController::create](/app/vendor/laravel/fortify/src/Http/Controllers/TwoFactorAuthenticatedSessionController.php)
                         */
                        export type Request = {    code?: string | null;
                            recovery_code?: string | null;}
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController::store](/app/vendor/laravel/fortify/src/Http/Controllers/TwoFactorAuthenticatedSessionController.php)
                         */
                        export type Request = {    code?: string | null;
                            recovery_code?: string | null;}
                    }
                }

                export namespace RegisteredUserController {
                    export namespace Create {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RegisteredUserController::create](/app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\RegisteredUserController::store](/app/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace EmailVerificationPromptController {
                    export namespace __invoke {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\EmailVerificationPromptController::__invoke](/app/vendor/laravel/fortify/src/Http/Controllers/EmailVerificationPromptController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace VerifyEmailController {
                    export namespace __invoke {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\VerifyEmailController::__invoke](/app/vendor/laravel/fortify/src/Http/Controllers/VerifyEmailController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace EmailVerificationNotificationController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\EmailVerificationNotificationController::store](/app/vendor/laravel/fortify/src/Http/Controllers/EmailVerificationNotificationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace ConfirmablePasswordController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmablePasswordController::show](/app/vendor/laravel/fortify/src/Http/Controllers/ConfirmablePasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmablePasswordController::store](/app/vendor/laravel/fortify/src/Http/Controllers/ConfirmablePasswordController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace ConfirmedPasswordStatusController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController::show](/app/vendor/laravel/fortify/src/Http/Controllers/ConfirmedPasswordStatusController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace TwoFactorAuthenticationController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController::store](/app/vendor/laravel/fortify/src/Http/Controllers/TwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }

                    export namespace Destroy {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController::destroy](/app/vendor/laravel/fortify/src/Http/Controllers/TwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace ConfirmedTwoFactorAuthenticationController {
                    export namespace Store {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\ConfirmedTwoFactorAuthenticationController::store](/app/vendor/laravel/fortify/src/Http/Controllers/ConfirmedTwoFactorAuthenticationController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }

                export namespace TwoFactorSecretKeyController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Fortify\Http\Controllers\TwoFactorSecretKeyController::show](/app/vendor/laravel/fortify/src/Http/Controllers/TwoFactorSecretKeyController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }
            }
        }
    }

    export namespace Sanctum {
        export namespace Http {
            export namespace Controllers {
                export namespace CsrfCookieController {
                    export namespace Show {
                        /**
                         * @see [\Laravel\Sanctum\Http\Controllers\CsrfCookieController::show](/app/vendor/laravel/sanctum/src/Http/Controllers/CsrfCookieController.php)
                         */
                        export type Request = Record<string, unknown>
                    }
                }
            }
        }
    }
}

export namespace Fruitcake {
    export namespace LaravelDebugbar {
        export namespace Controllers {
            export namespace OpenHandlerController {
                export namespace Handle {
                    /**
                     * @see [\Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::handle](/app/vendor/barryvdh/laravel-debugbar/src/Controllers/OpenHandlerController.php)
                     */
                    export type Request = {    op?: string | null;}
                }

                export namespace Clockwork {
                    /**
                     * @see [\Fruitcake\LaravelDebugbar\Controllers\OpenHandlerController::clockwork](/app/vendor/barryvdh/laravel-debugbar/src/Controllers/OpenHandlerController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace CacheController {
                export namespace Delete {
                    /**
                     * @see [\Fruitcake\LaravelDebugbar\Controllers\CacheController::delete](/app/vendor/barryvdh/laravel-debugbar/src/Controllers/CacheController.php)
                     */
                    export type Request = {    tags?: unknown[];
                        "tags.*"?: string;}
                }
            }

            export namespace QueriesController {
                export namespace Explain {
                    /**
                     * @see [\Fruitcake\LaravelDebugbar\Controllers\QueriesController::explain](/app/vendor/barryvdh/laravel-debugbar/src/Controllers/QueriesController.php)
                     */
                    export type Request = {    connection: string;
                        query: string;
                        bindings?: unknown[] | null;
                        hash: string;
                        mode?: "explain" | "visual" | "result" | null;
                        format?: string | null;}
                }
            }

            export namespace AssetController {
                export namespace GetAssets {
                    /**
                     * @see [\Fruitcake\LaravelDebugbar\Controllers\AssetController::getAssets](/app/vendor/barryvdh/laravel-debugbar/src/Controllers/AssetController.php)
                     */
                    export type Request = {    type: "js" | "css";}
                }
            }
        }
    }
}

export namespace Closure {
    export namespace __invoke {
        /**
         * @see [\Closure::__invoke](/[serialized-closure])
         */
        export type Request = Record<string, unknown>
    }
}

export namespace Illuminate {
    export namespace Routing {
        export namespace RedirectController {
            export namespace __invoke {
                /**
                 * @see [\Illuminate\Routing\RedirectController::__invoke](/app/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php)
                 */
                export type Request = Record<string, unknown>
            }
        }
    }
}