// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import HyperlinkController from "./HyperlinkController";
import Settings from "./Settings";

export const Controllers = {
    HyperlinkController,
    Settings,
}

export default Controllers