// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import AppController from "./AppController";
import HyperlinkController from "./HyperlinkController";
import PageController from "./PageController";
import Api from "./Api";
import Settings from "./Settings";

export const Controllers = {
    AppController,
    HyperlinkController,
    PageController,
    Api,
    Settings,
}

export default Controllers