// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import AuthenticatedSessionController from "./AuthenticatedSessionController";
import ConfirmablePasswordController from "./ConfirmablePasswordController";
import ConfirmedPasswordStatusController from "./ConfirmedPasswordStatusController";
import ConfirmedTwoFactorAuthenticationController from "./ConfirmedTwoFactorAuthenticationController";
import EmailVerificationNotificationController from "./EmailVerificationNotificationController";
import EmailVerificationPromptController from "./EmailVerificationPromptController";
import NewPasswordController from "./NewPasswordController";
import PasswordResetLinkController from "./PasswordResetLinkController";
import RecoveryCodeController from "./RecoveryCodeController";
import RegisteredUserController from "./RegisteredUserController";
import TwoFactorAuthenticatedSessionController from "./TwoFactorAuthenticatedSessionController";
import TwoFactorAuthenticationController from "./TwoFactorAuthenticationController";
import TwoFactorQrCodeController from "./TwoFactorQrCodeController";
import TwoFactorSecretKeyController from "./TwoFactorSecretKeyController";
import VerifyEmailController from "./VerifyEmailController";

export const Controllers = {
    AuthenticatedSessionController,
    ConfirmablePasswordController,
    ConfirmedPasswordStatusController,
    ConfirmedTwoFactorAuthenticationController,
    EmailVerificationNotificationController,
    EmailVerificationPromptController,
    NewPasswordController,
    PasswordResetLinkController,
    RecoveryCodeController,
    RegisteredUserController,
    TwoFactorAuthenticatedSessionController,
    TwoFactorAuthenticationController,
    TwoFactorQrCodeController,
    TwoFactorSecretKeyController,
    VerifyEmailController,
}

export default Controllers