// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import TwoFactorAuthenticatedSessionController from "./TwoFactorAuthenticatedSessionController";
import RecoveryCodeController from "./RecoveryCodeController";
import RegisteredUserController from "./RegisteredUserController";
import EmailVerificationPromptController from "./EmailVerificationPromptController";
import AuthenticatedSessionController from "./AuthenticatedSessionController";
import TwoFactorQrCodeController from "./TwoFactorQrCodeController";
import TwoFactorSecretKeyController from "./TwoFactorSecretKeyController";
import EmailVerificationNotificationController from "./EmailVerificationNotificationController";
import ConfirmablePasswordController from "./ConfirmablePasswordController";
import VerifyEmailController from "./VerifyEmailController";
import TwoFactorAuthenticationController from "./TwoFactorAuthenticationController";
import ConfirmedTwoFactorAuthenticationController from "./ConfirmedTwoFactorAuthenticationController";
import ConfirmedPasswordStatusController from "./ConfirmedPasswordStatusController";
import NewPasswordController from "./NewPasswordController";
import PasswordResetLinkController from "./PasswordResetLinkController";

export const Controllers = {
    TwoFactorAuthenticatedSessionController,
    RecoveryCodeController,
    RegisteredUserController,
    EmailVerificationPromptController,
    AuthenticatedSessionController,
    TwoFactorQrCodeController,
    TwoFactorSecretKeyController,
    EmailVerificationNotificationController,
    ConfirmablePasswordController,
    VerifyEmailController,
    TwoFactorAuthenticationController,
    ConfirmedTwoFactorAuthenticationController,
    ConfirmedPasswordStatusController,
    NewPasswordController,
    PasswordResetLinkController,
}

export default Controllers