// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\CacheController::delete
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/CacheController.php:16
 * @route "/_debugbar/cache/{key}"
 */
export const deleteMethod = (args: { key: string | number } | [ key: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: deleteMethod.url(args, options),
    method: "delete",
})

deleteMethod.definition = {
    methods: ["delete"],
    url: "/_debugbar/cache/{key}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\CacheController::delete
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/CacheController.php:16
 * @route "/_debugbar/cache/{key}"
 */
deleteMethod.url = (args: { key: string | number } | [ key: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { key: args }
    }
    
    if (Array.isArray(args)) {
        args = {
        key: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        key: args.key,
    }
    
    return deleteMethod.definition.url
        .replace("{key}", parsedArgs.key.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\CacheController::delete
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/CacheController.php:16
 * @route "/_debugbar/cache/{key}"
 */
deleteMethod.delete = (args: { key: string | number } | [ key: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: deleteMethod.url(args, options),
    method: "delete",
})



/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\CacheController::delete
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/CacheController.php:16
 * @route "/_debugbar/cache/{key}"
 */
const deleteMethodForm = (args: { key: string | number } | [ key: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: deleteMethod.url(args, formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \Fruitcake\LaravelDebugbar\Controllers\CacheController::delete
 * @see /app/vendor/barryvdh/laravel-debugbar/src/Controllers/CacheController.php:16
 * @route "/_debugbar/cache/{key}"
 */
deleteMethodForm.delete = (args: { key: string | number } | [ key: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: deleteMethod.url(args, formSafeOptions("delete", options)),
    method: "post",
})



deleteMethod.form = deleteMethodForm

const cache = {
    delete: deleteMethod,
}

export default cache