// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Debugbar from "./Debugbar";

export const Barryvdh = {
    Debugbar,
}

export default Barryvdh