// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, validateParameters, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \Barryvdh\Debugbar\Controllers\CacheController::delete
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\CacheController.php:13
 * @route "/_debugbar/cache/{key}/{tags?}"
 */
export const deleteMethod = (args: { key: string | number, tags?: string | number } | [ key: string | number, tags: string | number ], options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: deleteMethod.url(args, options),
    method: "delete",
})

deleteMethod.definition = {
    methods: ["delete"],
    url: "/_debugbar/cache/{key}/{tags?}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \Barryvdh\Debugbar\Controllers\CacheController::delete
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\CacheController.php:13
 * @route "/_debugbar/cache/{key}/{tags?}"
 */
deleteMethod.url = (args: { key: string | number, tags?: string | number } | [ key: string | number, tags: string | number ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
    args = {
        key: args[0],
        tags: args[1],
    }
}
    
    args = applyUrlDefaults(args)
    
    validateParameters(args, ["tags"])
    
    const parsedArgs = {
        key: args.key,
        tags: args.tags,
    }
    
    return deleteMethod.definition.url
        .replace("{key}", parsedArgs.key.toString())
        .replace("{tags?}", parsedArgs.tags?.toString() ?? '')
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \Barryvdh\Debugbar\Controllers\CacheController::delete
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\CacheController.php:13
 * @route "/_debugbar/cache/{key}/{tags?}"
 */
deleteMethod.delete = (args: { key: string | number, tags?: string | number } | [ key: string | number, tags: string | number ], options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: deleteMethod.url(args, options),
    method: "delete",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\CacheController::delete
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\CacheController.php:13
 * @route "/_debugbar/cache/{key}/{tags?}"
 */
const deleteMethodForm = (args: { key: string | number, tags?: string | number } | [ key: string | number, tags: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: deleteMethod.url(args, formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \Barryvdh\Debugbar\Controllers\CacheController::delete
 * @see \C:\Users\Clickadelic\dev-station\webdev-hq.com\webdev-hq.com\vendor\barryvdh\laravel-debugbar\src\Controllers\CacheController.php:13
 * @route "/_debugbar/cache/{key}/{tags?}"
 */
deleteMethodForm.delete = (args: { key: string | number, tags?: string | number } | [ key: string | number, tags: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: deleteMethod.url(args, formSafeOptions("delete", options)),
    method: "post",
})

deleteMethod.form = deleteMethodForm

const CacheController = {
    delete: deleteMethod,
}

export default CacheController