// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import AssetController from "./AssetController";
import CacheController from "./CacheController";
import OpenHandlerController from "./OpenHandlerController";
import QueriesController from "./QueriesController";

export const Controllers = {
    AssetController,
    CacheController,
    OpenHandlerController,
    QueriesController,
}

export default Controllers